package com.codercrew.HackConnect.config;

public class JwtConstant {


    public static final String SECRET_KEY = "ioofhghioearghiooehghiok dfgdhfghdgdfgdkjfgjkdfgjpdjgkjkdfgjkdgiouopggjdgjdkjgkdgkdgkdk dfgdjkfgjkdgkjdfghkdhkgkjdfgjkdfjkgjkdfgjkdfgdhfgjdhfghdg dsgdgdgfiodfhkgkdfgkdkjgkjdfgjkdjkfgkdfgkfkjdlgjkdfgjkdkjghjdfghjdghk dgodfhkgkdfgjkdfgkjsdfgjkldfjghjdfghjkdf iorfgieiohghioeghioeghioeihgjhigjiodigiodgioejigiogiogk jgijijghieghieegihhiedgdjgjidgojpkdjkbnkodgbjidigdn djgijopjighighi[dghiodhioghiodghdiofgjidfghjidfgjipodgjidgdnigbniodgnjonjobmnkodgmpkbjdgbdgnnkodfgniodnkognkodgnkdnkfgnkodngkondfnogkdngd dghiodgnhiogboupsdgndfhnoifbjo";

    public static final String JWT_HEADER = "Authorization";
}
